### ISSUE TITLE
Idea for mini project

### ISSUE THREAD

**Issue by cearhear** [colepjohn/MiniProject1#1]
My idea was to use a data set of music reviews from Pitchfork.com. I'm not sure what analysis I want to do exactly, but there are lots of directions to go. They are known to have some pretentious/harsh critics so sentiment analysis could be used to find these words,

**Comment by colepjohn** [comment]
I think this is a great idea. I am sure music reviews are also completed by passionate people so the data you collect will be very interesting. Maybe, you could compare multiple songs from one artist to another, to see what type of diction or wording fans of different artists use? Looking forward to it.
